In [1]:
import matplotlib.pyplot as plt
import os
import pandas as pd
import scanpy as sc
import squidpy as sq
import cv2
import matplotlib.pyplot as plt
import lazyslide as zs
from ipywidgets import interact, FloatSlider
import numpy as np
import glob

from pathlib import Path

# import sys
# sys.path.append('/work/PRTNR/CHUV/DIR/rgottar1/spatial/env/norkin_organoid/workflow/scripts')
# import coda
# import readwrite
# cfg = readwrite.config()

import sys
sys.path.append("/work/PRTNR/CHUV/DIR/rgottar1/spatial/env/lmcconn1")
from norkin_organoid.workflow.scripts.xenium.morphology_code.get_embeddings import (
    NorkinOrganoidDataset,
)

FEATURES_PATH = "/work/PRTNR/CHUV/DIR/rgottar1/spatial/env/lmcconn1/norkin_organoid/data/organoids_h&e/features_sdata"

%matplotlib inline
%load_ext autoreload
%autoreload 2

/work/PRTNR/CHUV/DIR/rgottar1/spatial/conda_envs/lazyslide_env/lib/python3.11/site-packages/dask/dataframe/__init__.py:31: FutureWarning: The legacy Dask DataFrame implementation is deprecated and will be removed in a future version. Set the configuration option `dataframe.query-planning` to `True` or None to enable the new Dask Dataframe implementation and silence this warning.
  warnings.warn(
/work/PRTNR/CHUV/DIR/rgottar1/spatial/conda_envs/lazyslide_env/lib/python3.11/site-packages/anndata/__init__.py:44: FutureWarning: Importing read_text from `anndata` is deprecated. Import anndata.io.read_text instead.
  return module_get_attr_redirect(attr_name, deprecated_mapping=_DEPRECATED)

In [2]:
# Load in the data
import glob
import os
import scanpy as sc
import anndata as ad
from tqdm import tqdm
import spatialdata as sd

sdata_paths = glob.glob(os.path.join(FEATURES_PATH, "*.zarr"))  # Adjust path if needed, e.g., "path/to/*.h5ad"
sdatas_dict = {}
adatas_list = []

for file_path in tqdm(sdata_paths):
    organoid_id = os.path.basename(file_path).replace('_features.zarr', '')
    sdata = sd.read_zarr(file_path)
    sdata.tables['features_adata'].obs['organoid_id'] = organoid_id
    adatas_list.append(sdata.tables['features_adata'])
    
    sdatas_dict[organoid_id] = sdata

# Merge all AnnData objects
merged_adata = ad.concat(adatas_list, join='outer', index_unique=None)
# merged_sdata = sd.concatenate({sdata.tables['features_adata'].obs['organoid_id'] : sdata for sdata in  sdatas_list}, join="outer")

# print(f"Merged AnnData shape: {merged_adata.shape}")
# print(f"Organoid IDs: {merged_adata.obs['organoid_id'].unique()}")

100%|██████████| 491/491 [03:37<00:00,  2.25it/s]
/work/PRTNR/CHUV/DIR/rgottar1/spatial/conda_envs/lazyslide_env/lib/python3.11/site-packages/anndata/_core/anndata.py:1791: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")

In [ ]:
def make_master_table(sdata):
    def delete_repeated_columns(df):
        return df.loc[:,~df.columns.duplicated()].copy()

    # make_master_table(sdata)
    tile_coords_xenium_absolute = sdata.shapes['tile_coords_xenium_absolute'] 
    tile_coords_xenium_absolute = tile_coords_xenium_absolute.rename(columns={'geometry': 'xenium_tile_geometry'})
    tile_coords_xenium_absolute = delete_repeated_columns(tile_coords_xenium_absolute)
    tile_coords_hne_absolute = sdata.shapes['tile_coords_hne_absolute'] 
    tile_coords_hne_absolute = tile_coords_hne_absolute.rename(columns={'geometry': 'hne_tile_geometry'})
    metadata_table = sdata['features_adata'].obs

    # metadata_table = metadata_table.merge(tile_coords_xenium_absolute, on=["tile_id", "tissue_id"], how="inner")
    metadata_table = metadata_table.merge(tile_coords_hne_absolute, on=["tile_id", "tissue_id"], how="inner")
    metadata_table = metadata_table.merge(tile_coords_xenium_absolute, on=["tile_id", "tissue_id"], how="inner")
    metadata_table['morphological_features'] = list(sdata.tables['features_adata'].X)

    cells_in_tile = sdata.shapes['cells_in_tile']
    cells_in_tile = cells_in_tile.rename(columns={"geometry": "cell_geometry"})
    cells_in_tile = cells_in_tile.drop(["index_right", 'component_and_cluster_and_lasso'], axis=1)

    return cells_in_tile.merge(metadata_table, on=["tile_id", "tissue_id"], how="inner")

In [ ]:
master_dfs = []

for sdata in tqdm(sdatas_dict.values()):
    try: 
        df = make_master_table(sdata)
        master_dfs.append(df)
    except Exception: 
        pass

 23%|██▎       | 111/491 [00:00<00:02, 181.95it/s]

> /tmp/ipykernel_402492/3118647228.py(25)make_master_table()
     21         cells_in_tile = cells_in_tile.drop(["index_right", 'component_and_cluster_and_lasso'], axis=1)
     22     except Exception as e:
     23         import pdb; pdb.set_trace()
     24
---> 25     return cells_in_tile.merge(metadata_table, on=["tile_id", "tissue_id"], how="inner")

100%|██████████| 491/491 [00:04<00:00, 101.91it/s]

[     cell_id                                      cell_geometry  \
 0        182  MULTIPOLYGON (((2167 2396, 2167 2395, 2168 239...
 1        182  MULTIPOLYGON (((2167 2396, 2167 2395, 2168 239...
 2        182  MULTIPOLYGON (((2167 2396, 2167 2395, 2168 239...
 3        205  MULTIPOLYGON (((2064 2360, 2064 2362, 2066 236...
 4        215  MULTIPOLYGON (((2165 2307, 2165 2308, 2164 230...
 ..       ...                                                ...
 572    13851  MULTIPOLYGON (((2110 2402, 2110 2403, 2111 240...
 573    13851  MULTIPOLYGON (((2110 2402, 2110 2403, 2111 240...
 574    13857  MULTIPOLYGON (((2112 2328, 2112 2332, 2115 233...
 575    13857  MULTIPOLYGON (((2112 2328, 2112 2332, 2115 233...
 576    13857  MULTIPOLYGON (((2112 2328, 2112 2332, 2115 233...

                                           full_cell_id patient_id  \
 0    proseg_expected_CRC_PDO_hImmune_v1_dapi_1HVQ_o...       1HVQ
 1    proseg_expected_CRC_PDO_hImmune_v1_dapi_1HVQ_o...       1HVQ
 2    proseg_expected_CRC_PDO_hImmune_v1_dapi_1HVQ_o...       1HVQ
 3    proseg_expected_CRC_PDO_hImmune_v1_dapi_1HVQ_o...       1HVQ
 4    proseg_expected_CRC_PDO_hImmune_v1_dapi_1HVQ_o...       1HVQ
 ..                                                 ...        ...
 572  proseg_expected_CRC_PDO_hImmune_v1_dapi_1HVQ_o...       1HVQ
 573  proseg_expected_CRC_PDO_hImmune_v1_dapi_1HVQ_o...       1HVQ
 574  proseg_expected_CRC_PDO_hImmune_v1_dapi_1HVQ_o...       1HVQ
 575  proseg_expected_CRC_PDO_hImmune_v1_dapi_1HVQ_o...       1HVQ
 576  proseg_expected_CRC_PDO_hImmune_v1_dapi_1HVQ_o...       1HVQ

               method               joint_id  tile_id  tissue_id  \
 0    hImmune_v1_dapi  hImmune_v1_dapi__1HVQ        2          0
 1    hImmune_v1_dapi  hImmune_v1_dapi__1HVQ        1          0
 2    hImmune_v1_dapi  hImmune_v1_dapi__1HVQ        0          0
 3    hImmune_v1_dapi  hImmune_v1_dapi__1HVQ        1          0
 4    hImmune_v1_dapi  hImmune_v1_dapi__1HVQ        2          0
 ..               ...                    ...      ...        ...
 572  hImmune_v1_dapi  hImmune_v1_dapi__1HVQ        1          0
 573  hImmune_v1_dapi  hImmune_v1_dapi__1HVQ        0          0
 574  hImmune_v1_dapi  hImmune_v1_dapi__1HVQ        2          0
 575  hImmune_v1_dapi  hImmune_v1_dapi__1HVQ        1          0
 576  hImmune_v1_dapi  hImmune_v1_dapi__1HVQ        0          0

                                            organoid_id  \
 0    proseg_expected_CRC_PDO_hImmune_v1_dapi_1HVQ_o...
 1    proseg_expected_CRC_PDO_hImmune_v1_dapi_1HVQ_o...
 2    proseg_expected_CRC_PDO_hImmune_v1_dapi_1HVQ_o...
 3    proseg_expected_CRC_PDO_hImmune_v1_dapi_1HVQ_o...
 4    proseg_expected_CRC_PDO_hImmune_v1_dapi_1HVQ_o...
 ..                                                 ...
 572  proseg_expected_CRC_PDO_hImmune_v1_dapi_1HVQ_o...
 573  proseg_expected_CRC_PDO_hImmune_v1_dapi_1HVQ_o...
 574  proseg_expected_CRC_PDO_hImmune_v1_dapi_1HVQ_o...
 575  proseg_expected_CRC_PDO_hImmune_v1_dapi_1HVQ_o...
 576  proseg_expected_CRC_PDO_hImmune_v1_dapi_1HVQ_o...

                                      hne_tile_geometry  \
 0    POLYGON ((22358 26884, 22358 28368, 20874 2836...
 1    POLYGON ((22358 26392, 22358 27876, 20874 2787...
 2    POLYGON ((21866 26884, 21866 28368, 20382 2836...
 3    POLYGON ((22358 26392, 22358 27876, 20874 2787...
 4    POLYGON ((22358 26884, 22358 28368, 20874 2836...
 ..                                                 ...
 572  POLYGON ((22358 26392, 22358 27876, 20874 2787...
 573  POLYGON ((21866 26884, 21866 28368, 20382 2836...
 574  POLYGON ((22358 26884, 22358 28368, 20874 2836...
 575  POLYGON ((22358 26392, 22358 27876, 20874 2787...
 576  POLYGON ((21866 26884, 21866 28368, 20382 2836...

                                   xenium_tile_geometry  \
 0    POLYGON ((2102.487 2274.84, 2231.746 2274.839,...
 1    POLYGON ((2059.633 2274.841, 2188.892 2274.839...
 2    POLYGON ((2102.488 2317.694, 2231.747 2317.693...
 3    POLYGON ((2059.633 2274.841, 2188.892 2274.839...
 4    POLYGON ((2102.487 2274.84, 2231.746 2274.839,...
 ..                                                 ...
 572  POLYGON ((2059.633 2274.841, 2188.892 2274.839...
 573  POLYGON ((2102.488 2317.694, 2231.747 2317.693...
 574  POLYGON ((2102.487 2274.84, 2231.746 2274.839,...
 575  POLYGON ((2059.633 2274.841, 2188.892 2274.839...
 576  POLYGON ((2102.488 2317.694, 2231.747 2317.693...

                                 morphological_features
 0    [0.2668, 0.152, 0.1252, 0.02736, 0.05884, -0.2...
 1    [0.03035, 0.0901, 0.0898, -0.02246, 0.1653, -0...
 2    [0.2262, 0.0764, 0.2095, 0.0673, 0.061, -0.279...
 3    [0.03035, 0.0901, 0.0898, -0.02246, 0.1653, -0...
 4    [0.2668, 0.152, 0.1252, 0.02736, 0.05884, -0.2...
 ..                                                 ...
 572  [0.03035, 0.0901, 0.0898, -0.02246, 0.1653, -0...
 573  [0.2262, 0.0764, 0.2095, 0.0673, 0.061, -0.279...
 574  [0.2668, 0.152, 0.1252, 0.02736, 0.05884, -0.2...
 575  [0.03035, 0.0901, 0.0898, -0.02246, 0.1653, -0...
 576  [0.2262, 0.0764, 0.2095, 0.0673, 0.061, -0.279...

 [577 rows x 12 columns],
      cell_id                                      cell_geometry  \
 0        231  MULTIPOLYGON (((4103 1475, 4103 1474, 4106 147...
 1        444  MULTIPOLYGON (((4122 1537, 4122 1541, 4123 154...
 2        637  MULTIPOLYGON (((4166 1552, 4166 1553, 4165 155...
 3        855  MULTIPOLYGON (((4106 1546, 4106 1551, 4107 155...
 4       1089  MULTIPOLYGON (((4206 1544, 4206 1545, 4207 154...
 ..       ...                                                ...
 119    35077  MULTIPOLYGON (((4121 1495, 4121 1496, 4120 149...
 120    35086  MULTIPOLYGON (((4153 1507, 4153 1508, 4152 150...
 121    35398  MULTIPOLYGON (((4121 1502, 4121 1503, 4120 150...
 122    35565  MULTIPOLYGON (((4216 1500, 4216 1501, 4215 150...
 123    35769  MULTIPOLYGON (((4113 1505, 4113 1504, 4116 150...

                                           full_cell_id patient_id  \
 0    proseg_expected_CRC_PDO_hImmune_v1_dapi_0LR9_o...       0LR9
 1    proseg_expected_CRC_PDO_hImmune_v1_dapi_0LR9_o...       0LR9
 2    proseg_expected_CRC_PDO_hImmune_v1_dapi_0LR9_o...       0LR9
 3    proseg_expected_CRC_PDO_hImmune_v1_dapi_0LR9_o...       0LR9
 4    proseg_expected_CRC_PDO_hImmune_v1_dapi_0LR9_o...       0LR9
 ..                                                 ...        ...
 119  proseg_expected_CRC_PDO_hImmune_v1_dapi_0LR9_o...       0LR9
 120  proseg_expected_CRC_PDO_hImmune_v1_dapi_0LR9_o...       0LR9
 121  proseg_expected_CRC_PDO_hImmune_v1_dapi_0LR9_o...       0LR9
 122  proseg_expected_CRC_PDO_hImmune_v1_dapi_0LR9_o...       0LR9
 123  proseg_expected_CRC_PDO_hImmune_v1_dapi_0LR9_o...       0LR9

               method               joint_id  tile_id  tissue_id  \
 0    hImmune_v1_dapi  hImmune_v1_dapi__0LR9        0          1
 1    hImmune_v1_dapi  hImmune_v1_dapi__0LR9        0          1
 2    hImmune_v1_dapi  hImmune_v1_dapi__0LR9        0          1
 3    hImmune_v1_dapi  hImmune_v1_dapi__0LR9        0          1
 4    hImmune_v1_dapi  hImmune_v1_dapi__0LR9        0          1
 ..               ...                    ...      ...        ...
 119  hImmune_v1_dapi  hImmune_v1_dapi__0LR9        0          1
 120  hImmune_v1_dapi  hImmune_v1_dapi__0LR9        0          1
 121  hImmune_v1_dapi  hImmune_v1_dapi__0LR9        0          1
 122  hImmune_v1_dapi  hImmune_v1_dapi__0LR9        0          1
 123  hImmune_v1_dapi  hImmune_v1_dapi__0LR9        0          1

                                            organoid_id  \
 0    proseg_expected_CRC_PDO_hImmune_v1_dapi_0LR9_o...
 1    proseg_expected_CRC_PDO_hImmune_v1_dapi_0LR9_o...
 2    proseg_expected_CRC_PDO_hImmune_v1_dapi_0LR9_o...
 3    proseg_expected_CRC_PDO_hImmune_v1_dapi_0LR9_o...
 4    proseg_expected_CRC_PDO_hImmune_v1_dapi_0LR9_o...
 ..                                                 ...
 119  proseg_expected_CRC_PDO_hImmune_v1_dapi_0LR9_o...
 120  proseg_expected_CRC_PDO_hImmune_v1_dapi_0LR9_o...
 121  proseg_expected_CRC_PDO_hImmune_v1_dapi_0LR9_o...
 122  proseg_expected_CRC_PDO_hImmune_v1_dapi_0LR9_o...
 123  proseg_expected_CRC_PDO_hImmune_v1_dapi_0LR9_o...

                                      hne_tile_geometry  \
 0    POLYGON ((48659 44638, 48659 46122, 47175 4612...
 1    POLYGON ((48659 44638, 48659 46122, 47175 4612...
 2    POLYGON ((48659 44638, 48659 46122, 47175 4612...
 3    POLYGON ((48659 44638, 48659 46122, 47175 4612...
 4    POLYGON ((48659 44638, 48659 46122, 47175 4612...
 ..                                                 ...
 119  POLYGON ((48659 44638, 48659 46122, 47175 4612...
 120  POLYGON ((48659 44638, 48659 46122, 47175 4612...
 121  POLYGON ((48659 44638, 48659 46122, 47175 4612...
 122  POLYGON ((48659 44638, 48659 46122, 47175 4612...
 123  POLYGON ((48659 44638, 48659 46122, 47175 4612...

                                   xenium_tile_geometry  \
 0    POLYGON ((4080.61 1456.362, 4209.417 1455.524,...
 1    POLYGON ((4080.61 1456.362, 4209.417 1455.524,...
 2    POLYGON ((4080.61 1456.362, 4209.417 1455.524,...
 3    POLYGON ((4080.61 1456.362, 4209.417 1455.524,...
 4    POLYGON ((4080.61 1456.362, 4209.417 1455.524,...
 ..                                                 ...
 119  POLYGON ((4080.61 1456.362, 4209.417 1455.524,...
 120  POLYGON ((4080.61 1456.362, 4209.417 1455.524,...
 121  POLYGON ((4080.61 1456.362, 4209.417 1455.524,...
 122  POLYGON ((4080.61 1456.362, 4209.417 1455.524,...
 123  POLYGON ((4080.61 1456.362, 4209.417 1455.524,...

                                 morphological_features
 0    [-0.03047, 0.09985, 0.2235, 0.1913, 0.4548, -0...
 1    [-0.03047, 0.09985, 0.2235, 0.1913, 0.4548, -0...
 2    [-0.03047, 0.09985, 0.2235, 0.1913, 0.4548, -0...
 3    [-0.03047, 0.09985, 0.2235, 0.1913, 0.4548, -0...
 4    [-0.03047, 0.09985, 0.2235, 0.1913, 0.4548, -0...
 ..                                                 ...
 119  [-0.03047, 0.09985, 0.2235, 0.1913, 0.4548, -0...
 120  [-0.03047, 0.09985, 0.2235, 0.1913, 0.4548, -0...
 121  [-0.03047, 0.09985, 0.2235, 0.1913, 0.4548, -0...
 122  [-0.03047, 0.09985, 0.2235, 0.1913, 0.4548, -0...
 123  [-0.03047, 0.09985, 0.2235, 0.1913, 0.4548, -0...

 [124 rows x 12 columns],
      cell_id                                      cell_geometry  \
 0          1  MULTIPOLYGON (((4664 2464, 4664 2465, 4665 246...
 1         72  MULTIPOLYGON (((4673 2474, 4673 2473, 4674 247...
 2        135  MULTIPOLYGON (((4682 2364, 4682 2363, 4683 236...
 3        335  MULTIPOLYGON (((4765 2486, 4765 2484, 4766 248...
 4        411  MULTIPOLYGON (((4790 2423, 4790 2422, 4792 242...
 ..       ...                                                ...
 139    20788  MULTIPOLYGON (((4678 2466, 4678 2468, 4680 246...
 140    20960  MULTIPOLYGON (((4768 2374, 4768 2375, 4767 237...
 141    21057  MULTIPOLYGON (((4692 2416, 4692 2418, 4693 241...
 142    21178  MULTIPOLYGON (((4756 2396, 4756 2397, 4754 239...
 143    21584  MULTIPOLYGON (((4666 2366, 4666 2358, 4667 235...

                                           full_cell_id patient_id  \
 0    proseg_expected_CRC_PDO_hImmune_v1_dapi_131N_o...       131N
 1    proseg_expected_CRC_PDO_hImmune_v1_dapi_131N_o...       131N
 2    proseg_expected_CRC_PDO_hImmune_v1_dapi_131N_o...       131N
 3    proseg_expected_CRC_PDO_hImmune_v1_dapi_131N_o...       131N
 4    proseg_expected_CRC_PDO_hImmune_v1_dapi_131N_o...       131N
 ..                                                 ...        ...
 139  proseg_expected_CRC_PDO_hImmune_v1_dapi_131N_o...       131N
 140  proseg_expected_CRC_PDO_hImmune_v1_dapi_131N_o...       131N
 141  proseg_expected_CRC_PDO_hImmune_v1_dapi_131N_o...       131N
 142  proseg_expected_CRC_PDO_hImmune_v1_dapi_131N_o...       131N
 143  proseg_expected_CRC_PDO_hImmune_v1_dapi_131N_o...       131N

               method               joint_id  tile_id  tissue_id  \
 0    hImmune_v1_dapi  hImmune_v1_dapi__131N        0          3
 1    hImmune_v1_dapi  hImmune_v1_dapi__131N        0          3
 2    hImmune_v1_dapi  hImmune_v1_dapi__131N        0          3
 3    hImmune_v1_dapi  hImmune_v1_dapi__131N        0          3
 4    hImmune_v1_dapi  hImmune_v1_dapi__131N        0          3
 ..               ...                    ...      ...        ...
 139  hImmune_v1_dapi  hImmune_v1_dapi__131N        0          3
 140  hImmune_v1_dapi  hImmune_v1_dapi__131N        0          3
 141  hImmune_v1_dapi  hImmune_v1_dapi__131N        0          3
 142  hImmune_v1_dapi  hImmune_v1_dapi__131N        0          3
 143  hImmune_v1_dapi  hImmune_v1_dapi__131N        0          3

                                            organoid_id  \
 0    proseg_expected_CRC_PDO_hImmune_v1_dapi_131N_o...
 1    proseg_expected_CRC_PDO_hImmune_v1_dapi_131N_o...
 2    proseg_expected_CRC_PDO_hImmune_v1_dapi_131N_o...
 3    proseg_expected_CRC_PDO_hImmune_v1_dapi_131N_o...
 4    proseg_expected_CRC_PDO_hImmune_v1_dapi_131N_o...
 ..                                                 ...
 139  proseg_expected_CRC_PDO_hImmune_v1_dapi_131N_o...
 140  proseg_expected_CRC_PDO_hImmune_v1_dapi_131N_o...
 141  proseg_expected_CRC_PDO_hImmune_v1_dapi_131N_o...
 142  proseg_expected_CRC_PDO_hImmune_v1_dapi_131N_o...
 143  proseg_expected_CRC_PDO_hImmune_v1_dapi_131N_o...

                                      hne_tile_geometry  \
 0    POLYGON ((23836 43513, 23836 44997, 22352 4499...
 1    POLYGON ((23836 43513, 23836 44997, 22352 4499...
 2    POLYGON ((23836 43513, 23836 44997, 22352 4499...
 3    POLYGON ((23836 43513, 23836 44997, 22352 4499...
 4    POLYGON ((23836 43513, 23836 44997, 22352 4499...
 ..                                                 ...
 139  POLYGON ((23836 43513, 23836 44997, 22352 4499...
 140  POLYGON ((23836 43513, 23836 44997, 22352 4499...
 141  POLYGON ((23836 43513, 23836 44997, 22352 4499...
 142  POLYGON ((23836 43513, 23836 44997, 22352 4499...
 143  POLYGON ((23836 43513, 23836 44997, 22352 4499...

                                   xenium_tile_geometry  \
 0    POLYGON ((4662.046 2364.836, 4791.398 2364.527...
 1    POLYGON ((4662.046 2364.836, 4791.398 2364.527...
 2    POLYGON ((4662.046 2364.836, 4791.398 2364.527...
 3    POLYGON ((4662.046 2364.836, 4791.398 2364.527...
 4    POLYGON ((4662.046 2364.836, 4791.398 2364.527...
 ..                                                 ...
 139  POLYGON ((4662.046 2364.836, 4791.398 2364.527...
 140  POLYGON ((4662.046 2364.836, 4791.398 2364.527...
 141  POLYGON ((4662.046 2364.836, 4791.398 2364.527...
 142  POLYGON ((4662.046 2364.836, 4791.398 2364.527...
 143  POLYGON ((4662.046 2364.836, 4791.398 2364.527...

                                 morphological_features
 0    [0.1103, 0.2062, 0.3503, 0.3022, -0.02995, -0....
 1    [0.1103, 0.2062, 0.3503, 0.3022, -0.02995, -0....
 2    [0.1103, 0.2062, 0.3503, 0.3022, -0.02995, -0....
 3    [0.1103, 0.2062, 0.3503, 0.3022, -0.02995, -0....
 4    [0.1103, 0.2062, 0.3503, 0.3022, -0.02995, -0....
 ..                                                 ...
 139  [0.1103, 0.2062, 0.3503, 0.3022, -0.02995, -0....
 140  [0.1103, 0.2062, 0.3503, 0.3022, -0.02995, -0....
 141  [0.1103, 0.2062, 0.3503, 0.3022, -0.02995, -0....
 142  [0.1103, 0.2062, 0.3503, 0.3022, -0.02995, -0....
 143  [0.1103, 0.2062, 0.3503, 0.3022, -0.02995, -0....

 [144 rows x 12 columns],
      cell_id                                      cell_geometry  \
 0          4  MULTIPOLYGON (((1254 1224, 1254 1225, 1253 122...
 1          4  MULTIPOLYGON (((1254 1224, 1254 1225, 1253 122...
 2          4  MULTIPOLYGON (((1254 1224, 1254 1225, 1253 122...
 3         28  MULTIPOLYGON (((1238 1226, 1238 1227, 1237 122...
 4         28  MULTIPOLYGON (((1238 1226, 1238 1227, 1237 122...
 ..       ...                                                ...
 849    34147  MULTIPOLYGON (((1215 1328, 1215 1329, 1217 132...
 850    34259  MULTIPOLYGON (((1340 1346, 1340 1345, 1341 134...
 851    34259  MULTIPOLYGON (((1340 1346, 1340 1345, 1341 134...
 852    34777  MULTIPOLYGON (((1328 1354, 1328 1356, 1329 135...
 853    34777  MULTIPOLYGON (((1328 1354, 1328 1356, 1329 135...

                                           full_cell_id patient_id  \
 0    proseg_expected_CRC_PDO_hImmune_v1_dapi_14PT_o...       14PT
 1    proseg_expected_CRC_PDO_hImmune_v1_dapi_14PT_o...       14PT
 2    proseg_expected_CRC_PDO_hImmune_v1_dapi_14PT_o...       14PT
 3    proseg_expected_CRC_PDO_hImmune_v1_dapi_14PT_o...       14PT
 4    proseg_expected_CRC_PDO_hImmune_v1_dapi_14PT_o...       14PT
 ..                                                 ...        ...
 849  proseg_expected_CRC_PDO_hImmune_v1_dapi_14PT_o...       14PT
 850  proseg_expected_CRC_PDO_hImmune_v1_dapi_14PT_o...       14PT
 851  proseg_expected_CRC_PDO_hImmune_v1_dapi_14PT_o...       14PT
 852  proseg_expected_CRC_PDO_hImmune_v1_dapi_14PT_o...       14PT
 853  proseg_expected_CRC_PDO_hImmune_v1_dapi_14PT_o...       14PT

               method               joint_id  tile_id  tissue_id  \
 0    hImmune_v1_dapi  hImmune_v1_dapi__14PT        3          0
 1    hImmune_v1_dapi  hImmune_v1_dapi__14PT        2          0
 2    hImmune_v1_dapi  hImmune_v1_dapi__14PT        1          0
 3    hImmune_v1_dapi  hImmune_v1_dapi__14PT        3          0
 4    hImmune_v1_dapi  hImmune_v1_dapi__14PT        2          0
 ..               ...                    ...      ...        ...
 849  hImmune_v1_dapi  hImmune_v1_dapi__14PT        0          0
 850  hImmune_v1_dapi  hImmune_v1_dapi__14PT        1          0
 851  hImmune_v1_dapi  hImmune_v1_dapi__14PT        0          0
 852  hImmune_v1_dapi  hImmune_v1_dapi__14PT        1          0
 853  hImmune_v1_dapi  hImmune_v1_dapi__14PT        0          0

                                            organoid_id  \
 0    proseg_expected_CRC_PDO_hImmune_v1_dapi_14PT_o...
 1    proseg_expected_CRC_PDO_hImmune_v1_dapi_14PT_o...
 2    proseg_expected_CRC_PDO_hImmune_v1_dapi_14PT_o...
 3    proseg_expected_CRC_PDO_hImmune_v1_dapi_14PT_o...
 4    proseg_expected_CRC_PDO_hImmune_v1_dapi_14PT_o...
 ..                                                 ...
 849  proseg_expected_CRC_PDO_hImmune_v1_dapi_14PT_o...
 850  proseg_expected_CRC_PDO_hImmune_v1_dapi_14PT_o...
 851  proseg_expected_CRC_PDO_hImmune_v1_dapi_14PT_o...
 852  proseg_expected_CRC_PDO_hImmune_v1_dapi_14PT_o...
 853  proseg_expected_CRC_PDO_hImmune_v1_dapi_14PT_o...

                                      hne_tile_geometry  \
 0    POLYGON ((45981 12052, 45981 13536, 44497 1353...
 1    POLYGON ((45489 12544, 45489 14028, 44005 1402...
 2    POLYGON ((44997 12544, 44997 14028, 43513 1402...
 3    POLYGON ((45981 12052, 45981 13536, 44497 1353...
 4    POLYGON ((45489 12544, 45489 14028, 44005 1402...
 ..                                                 ...
 849  POLYGON ((44505 12544, 44505 14028, 43021 1402...
 850  POLYGON ((44997 12544, 44997 14028, 43513 1402...
 851  POLYGON ((44505 12544, 44505 14028, 43021 1402...
 852  POLYGON ((44997 12544, 44997 14028, 43513 1402...
 853  POLYGON ((44505 12544, 44505 14028, 43021 1402...

                                   xenium_tile_geometry  \
 0    POLYGON ((1170.095 1145.146, 1299.332 1145.139...
 1    POLYGON ((1212.944 1187.99, 1342.181 1187.983,...
 2    POLYGON ((1212.946 1230.837, 1342.183 1230.83,...
 3    POLYGON ((1170.095 1145.146, 1299.332 1145.139...
 4    POLYGON ((1212.944 1187.99, 1342.181 1187.983,...
 ..                                                 ...
 849  POLYGON ((1212.949 1273.684, 1342.186 1273.676...
 850  POLYGON ((1212.946 1230.837, 1342.183 1230.83,...
 851  POLYGON ((1212.949 1273.684, 1342.186 1273.676...
 852  POLYGON ((1212.946 1230.837, 1342.183 1230.83,...
 853  POLYGON ((1212.949 1273.684, 1342.186 1273.676...

                                 morphological_features
 0    [0.1372, -0.04538, 0.2029, 0.2166, 0.1653, -0....
 1    [0.2698, 0.01692, 0.1376, 0.2874, 0.1895, -0.2...
 2    [0.3108, -0.03653, 0.07324, 0.286, 0.3284, -0....
 3    [0.1372, -0.04538, 0.2029, 0.2166, 0.1653, -0....

In [95]:
master_df = pd.concat(master_dfs, ignore_index=True)
master_df.to_parquet("/work/PRTNR/CHUV/DIR/rgottar1/spatial/env/lmcconn1/norkin_organoid/data/organoids_h&e/all_data.parquet", index=False)

In [98]:
df = pd.read_parquet("/work/PRTNR/CHUV/DIR/rgottar1/spatial/env/lmcconn1/norkin_organoid/data/organoids_h&e/all_data.parquet")
print(df.columns)
df.head()

Index(['cell_id', 'cell_geometry', 'full_cell_id', 'patient_id', 'method',
       'joint_id', 'tile_id', 'tissue_id', 'organoid_id', 'hne_tile_geometry',
       'xenium_tile_geometry', 'morphological_features'],
      dtype='object')

,cell_id,cell_geometry,full_cell_id,patient_id,method,joint_id,tile_id,tissue_id,organoid_id,hne_tile_geometry,xenium_tile_geometry,morphological_features
0,182,b'\x01\x06\x00\x00\x00\x02\x00\x00\x00\x01\x03...,proseg_expected_CRC_PDO_hImmune_v1_dapi_1HVQ_o...,1HVQ,hImmune_v1_dapi,hImmune_v1_dapi__1HVQ,2,0,proseg_expected_CRC_PDO_hImmune_v1_dapi_1HVQ_o...,b'\x01\x03\x00\x00\x00\x01\x00\x00\x00\x05\x00...,"b""\x01\x03\x00\x00\x00\x01\x00\x00\x00\x05\x00...","[0.2668, 0.152, 0.1252, 0.02736, 0.05884, -0.2..."
1,182,b'\x01\x06\x00\x00\x00\x02\x00\x00\x00\x01\x03...,proseg_expected_CRC_PDO_hImmune_v1_dapi_1HVQ_o...,1HVQ,hImmune_v1_dapi,hImmune_v1_dapi__1HVQ,1,0,proseg_expected_CRC_PDO_hImmune_v1_dapi_1HVQ_o...,b'\x01\x03\x00\x00\x00\x01\x00\x00\x00\x05\x00...,b'\x01\x03\x00\x00\x00\x01\x00\x00\x00\x05\x00...,"[0.03035, 0.0901, 0.0898, -0.02246, 0.1653, -0..."
2,182,b'\x01\x06\x00\x00\x00\x02\x00\x00\x00\x01\x03...,proseg_expected_CRC_PDO_hImmune_v1_dapi_1HVQ_o...,1HVQ,hImmune_v1_dapi,hImmune_v1_dapi__1HVQ,0,0,proseg_expected_CRC_PDO_hImmune_v1_dapi_1HVQ_o...,b'\x01\x03\x00\x00\x00\x01\x00\x00\x00\x05\x00...,b'\x01\x03\x00\x00\x00\x01\x00\x00\x00\x05\x00...,"[0.2262, 0.0764, 0.2095, 0.0673, 0.061, -0.279..."
3,205,b'\x01\x06\x00\x00\x00\x01\x00\x00\x00\x01\x03...,proseg_expected_CRC_PDO_hImmune_v1_dapi_1HVQ_o...,1HVQ,hImmune_v1_dapi,hImmune_v1_dapi__1HVQ,1,0,proseg_expected_CRC_PDO_hImmune_v1_dapi_1HVQ_o...,b'\x01\x03\x00\x00\x00\x01\x00\x00\x00\x05\x00...,b'\x01\x03\x00\x00\x00\x01\x00\x00\x00\x05\x00...,"[0.03035, 0.0901, 0.0898, -0.02246, 0.1653, -0..."
4,215,b'\x01\x06\x00\x00\x00\x02\x00\x00\x00\x01\x03...,proseg_expected_CRC_PDO_hImmune_v1_dapi_1HVQ_o...,1HVQ,hImmune_v1_dapi,hImmune_v1_dapi__1HVQ,2,0,proseg_expected_CRC_PDO_hImmune_v1_dapi_1HVQ_o...,b'\x01\x03\x00\x00\x00\x01\x00\x00\x00\x05\x00...,"b""\x01\x03\x00\x00\x00\x01\x00\x00\x00\x05\x00...","[0.2668, 0.152, 0.1252, 0.02736, 0.05884, -0.2..."

In [ ]:
cells_in_tile = sdata.shapes['cells_in_tile']
cells_in_tile = cells_in_tile.rename(columns={"geometry": "cell_geometry"})
cells_in_tile = cells_in_tile.drop(["index_right", 'component_and_cluster_and_lasso'], axis=1)
cells_in_tile.head()

,cell_id,cell_geometry,full_cell_id,patient_id,method,joint_id,tile_id,tissue_id
8,8,"MULTIPOLYGON (((2080 1959, 2080 1958, 2081 195...",proseg_expected_CRC_PDO_hImmune_v1_dapi_1J25_o...,1J25,hImmune_v1_dapi,hImmune_v1_dapi__1J25,1,2
8,8,"MULTIPOLYGON (((2080 1959, 2080 1958, 2081 195...",proseg_expected_CRC_PDO_hImmune_v1_dapi_1J25_o...,1J25,hImmune_v1_dapi,hImmune_v1_dapi__1J25,0,2
159,159,"MULTIPOLYGON (((1995 1889, 1995 1888, 1997 188...",proseg_expected_CRC_PDO_hImmune_v1_dapi_1J25_o...,1J25,hImmune_v1_dapi,hImmune_v1_dapi__1J25,3,2
159,159,"MULTIPOLYGON (((1995 1889, 1995 1888, 1997 188...",proseg_expected_CRC_PDO_hImmune_v1_dapi_1J25_o...,1J25,hImmune_v1_dapi,hImmune_v1_dapi__1J25,2,2
159,159,"MULTIPOLYGON (((1995 1889, 1995 1888, 1997 188...",proseg_expected_CRC_PDO_hImmune_v1_dapi_1J25_o...,1J25,hImmune_v1_dapi,hImmune_v1_dapi__1J25,1,2

In [ ]:
sample_organoid_id, sample_sdata = list(sdatas_dict.items())[0]
sample_sdata['cells_in_tile']
#full_cell_id, tile_id, tissue_id, component_and_cluster_and_lasso

,cell_id,geometry,full_cell_id,patient_id,method,joint_id,component_and_cluster_and_lasso,index_right,tile_id,tissue_id
182,182,"MULTIPOLYGON (((2167 2396, 2167 2395, 2168 239...",proseg_expected_CRC_PDO_hImmune_v1_dapi_1HVQ_o...,1HVQ,hImmune_v1_dapi,hImmune_v1_dapi__1HVQ,proseg_expected_CRC_PDO_hImmune_v1_dapi_1HVQ_o...,2,2,0
182,182,"MULTIPOLYGON (((2167 2396, 2167 2395, 2168 239...",proseg_expected_CRC_PDO_hImmune_v1_dapi_1HVQ_o...,1HVQ,hImmune_v1_dapi,hImmune_v1_dapi__1HVQ,proseg_expected_CRC_PDO_hImmune_v1_dapi_1HVQ_o...,1,1,0
182,182,"MULTIPOLYGON (((2167 2396, 2167 2395, 2168 239...",proseg_expected_CRC_PDO_hImmune_v1_dapi_1HVQ_o...,1HVQ,hImmune_v1_dapi,hImmune_v1_dapi__1HVQ,proseg_expected_CRC_PDO_hImmune_v1_dapi_1HVQ_o...,0,0,0
205,205,"MULTIPOLYGON (((2064 2360, 2064 2362, 2066 236...",proseg_expected_CRC_PDO_hImmune_v1_dapi_1HVQ_o...,1HVQ,hImmune_v1_dapi,hImmune_v1_dapi__1HVQ,proseg_expected_CRC_PDO_hImmune_v1_dapi_1HVQ_o...,1,1,0
215,215,"MULTIPOLYGON (((2165 2307, 2165 2308, 2164 230...",proseg_expected_CRC_PDO_hImmune_v1_dapi_1HVQ_o...,1HVQ,hImmune_v1_dapi,hImmune_v1_dapi__1HVQ,proseg_expected_CRC_PDO_hImmune_v1_dapi_1HVQ_o...,2,2,0
...,...,...,...,...,...,...,...,...,...,...
13851,13851,"MULTIPOLYGON (((2110 2402, 2110 2403, 2111 240...",proseg_expected_CRC_PDO_hImmune_v1_dapi_1HVQ_o...,1HVQ,hImmune_v1_dapi,hImmune_v1_dapi__1HVQ,proseg_expected_CRC_PDO_hImmune_v1_dapi_1HVQ_o...,1,1,0
13851,13851,"MULTIPOLYGON (((2110 2402, 2110 2403, 2111 240...",proseg_expected_CRC_PDO_hImmune_v1_dapi_1HVQ_o...,1HVQ,hImmune_v1_dapi,hImmune_v1_dapi__1HVQ,proseg_expected_CRC_PDO_hImmune_v1_dapi_1HVQ_o...,0,0,0
13857,13857,"MULTIPOLYGON (((2112 2328, 2112 2332, 2115 233...",proseg_expected_CRC_PDO_hImmune_v1_dapi_1HVQ_o...,1HVQ,hImmune_v1_dapi,hImmune_v1_dapi__1HVQ,proseg_expected_CRC_PDO_hImmune_v1_dapi_1HVQ_o...,2,2,0
13857,13857,"MULTIPOLYGON (((2112 2328, 2112 2332, 2115 233...",proseg_expected_CRC_PDO_hImmune_v1_dapi_1HVQ_o...,1HVQ,hImmune_v1_dapi,hImmune_v1_dapi__1HVQ,proseg_expected_CRC_PDO_hImmune_v1_dapi_1HVQ_o...,1,1,0
13857,13857,"MULTIPOLYGON (((2112 2328, 2112 2332, 2115 233...",proseg_expected_CRC_PDO_hImmune_v1_dapi_1HVQ_o...,1HVQ,hImmune_v1_dapi,hImmune_v1_dapi__1HVQ,proseg_expected_CRC_PDO_hImmune_v1_dapi_1HVQ_o...,0,0,0

In [ ]:
# output format: cell, tile, organoid, representation
entries = {}

for organoid_id, sdata in sdatas_dict.items():
    for entry in sdata.tables['cell']